language: node_js
node_js:
  - 'lts/*'
services:
  - mysql

env:
  - NODE_ENV=test

cache:
  directories:
    - '$HOME/.npm'
    - '$HOME/.pkg-cache'

install:
  - npm ci

before_script:
  - mysql -e 'CREATE DATABASE `anna-test`;'

script:
  - npm run coverage
  - npm run eslint
  - npm run build:package

notifications:
  email:
    on_success: never
