language: node_js
node_js:
  - 'lts/*'
services:
  - mysql
cache:
  directories:
    - '$HOME/.npm'
env:
  - NODE_ENV=development

install:
  - npm ci

before_script:
  - mysql -e 'CREATE DATABASE anna;'
  - npm run db:migrate

script:
  - npm run coverage
  - npm run eslint

notifications:
  email:
    on_success: never
