language: node_js
node_js:
  - 'lts/*'
services:
  - mysql

git:
  depth: 1

cache:
  directories:
    - '$HOME/.npm'

install:
  - npm ci

before_script:
  - mysql -e 'CREATE DATABASE anna;'
  - npm run db:migrate

script:
  - npm run coverage
  - npm run eslint
  - npm run build:package

notifications:
  email:
    on_success: never
