version: '3'
services:
  mongodb:
    image: mongo:2.4.14
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "127.0.0.1:27017:27017"