version: '3'
services:
  db:
    image: mariadb:10.3
    container_name: 'anna-databases'
    volumes:
      - ./docker/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - '127.0.0.1:3306:3306'
