version: '3'
services:
  db:
    image: mariadb:10.1.26
    container_name: "mariadb"
    environment:
      - MYSQL_DATABASE=anna
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - "127.0.0.1:3306:3306"