name: Validate

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    services:
      mariadb:
        image: mariadb:10.3
        ports:
          - 127.0.0.1:3306:3306
        env:
          MYSQL_DATABASE: anna_test
          MYSQL_ROOT_PASSWORD:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run migration
        run: npm run lerna run db:migrate

      - name: Run lint check
        run: npm run lint:check

      - name: Run format check
        run: npm run format:check

      - name: unit tests
        run: npm run coverage

      - name: Run type check
        run: npm run type:check

      - name: Build
        run: npm run lerna run build:release

  release:
    needs: main
    runs-on: ubuntu-latest
    if: ${{ contains('refs/heads/master', github.ref) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_ACCESS_TOKEN }}
        run: npx -p semantic-release -p conventional-changelog-conventionalcommits -c semantic-release
